# Generated by Django 5.0.7 on 2024-07-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0004_producto_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('caracteristica', models.TextField()),
            ],
        ),
    ]
