# Generated by Django 5.0.7 on 2024-07-29 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0005_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='sector_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='Market.sector'),
        ),
    ]
