# Generated by Django 5.0.7 on 2024-07-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0006_proveedor_sector_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='sector',
        ),
    ]
