# Generated by Django 5.0.7 on 2024-07-29 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0007_remove_proveedor_sector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='marca',
            new_name='marcas',
        ),
    ]
