# Generated by Django 4.2.3 on 2024-08-15 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0009_cliente_rename_marcas_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_factura',
            old_name='producto_id_id',
            new_name='producto_id',
        ),
    ]
