name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd ./MarketProject
        pip install -r requirements.txt

    - name: Run migrations
      run: |
        cd ./MarketProject
        python manage.py migrate

    - name: Set up Python path
      run: echo "PYTHONPATH=$(pwd)/MarketProject" >> $GITHUB_ENV
        
    - name: Run tests
      env:
        DJANGO_SETTINGS_MODULE: MarketProject.settings
      run: |
        pytest --cov=. --cov-report=xml

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
          args: >
            -Dsonar.projectKey=JulianL48_Django-CI
            -Dsonar.organization=julianl48
            -Dsonar.sources=./MarketProject
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.branch.name=main
      env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml